### ISSUE TITLE
Generate HCL from Flux manifests

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/terraform-provider-flux#183]
We should look into running https://github.com/jrhouston/tfk8s in CI and generate HCL from the Flux manifestgen output, this way we could get rid of the kubectl provider and avoid all the issues with dealing with YAML in TF.

**Comment by stefanprodan** [comment]
This would enable air-gapped installations https://github.com/fluxcd/flux2/discussions/1692

**Comment by rupelu** [comment]
I would be interested, as my current workaround is to download the generated manifests while still online (non-air-gapped). So basically what I am doing is to run things like `terraform init` and `terraform apply -target=some_resources` so that everything gets downloaded what I need for an offline installation. Then the full folder with all the possibly generated files and with the **.terraform** folder is brought to an air-gapped environment. There again a `terraform apply` is run to setup kubernetes clusters and flux itself.

To get a bit more clarification [here is a gist](https://gist.github.com/rupelu/7f08d8a9b6bc5d540f656cf9dfdc11cf) showing how I do this for flux. Resources named like *_before_packaging (and all datasources/resources they depend on) will be run in the non-air-gapped phase. This enables me to download the manifests before going air-gapped.

It would be an improvement to not have such a workaround and error potential in the setup of flux.

**Comment by wjam** [comment]
It isn't a good idea to manage the Kubernetes cluster and the resources running within it in the same state - https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#stacking-with-managed-kubernetes-cluster-resources. They should be managed within completely distinct states otherwise Bad Things May Happen.

**Comment by stefanprodan** [comment]
Ok closing this
