### ISSUE TITLE
Provide Module

### ISSUE THREAD

**Issue by RichiCoder1** [fluxcd/terraform-provider-flux#27]
Right now this Repo requires you to manually put the data sources together with other provides to actually install the Flux components. One thing that might be help in addition to examples is a module that actually puts together this provider and the kubernetes (alpha) provider in an end-to-end experience.

If this sounds good, I would be willing to chip in on this.

**Comment by phillebaba** [comment]
I am not sure how we would deal with modules, not because they are not useful but because there are a ton of different use cases. People may use a bunch of different git and Kuberentes providers. At the same time we want to give the best experience for end users so that they can easily use this provider. The risk is that everyone ends up building their own modules that float around on the internet causing confusion. It might just be to early to start maintaining modules before we have a better grasp on the use cases. If you end up creating a module please link it here so I can take a look at it!

In regards to the Kubernetes provider I don't think I can recommend anyone to use the Kubernetes provider as it is in alpha and does not recommenced production use. Then again relying on a 3rd party provider isn't great either. This is something we are looking into how to solve in a better way.

**Comment by RichiCoder1** [comment]
Sounds good! Once There's a migration path for our stuff from v1, I'll make sure we put the resulting module somewhere referenceable.

**Comment by phillebaba** [comment]
So looping back to this discussion I think that as multi tenancy becomes more and more complicated it might become more relevant to create modules. The issue right now is figuring out how opinionated the modules should be, and how to deal with provider versioning.

It might also be smart to wait until the findings regarding multi tenancy security is completed.

**Comment by phillebaba** [comment]
Closing for now until somebody adds usable modules.

**Comment by winniegakuru** [comment]
any feedback on modules?
