### ISSUE TITLE
How to delete resources created by flux?

### ISSUE THREAD

**Issue by dhw362177** [fluxcd/terraform-provider-flux#344]
Hi guys

Currently I'm using terraform to deploy flux, but I found that when I deleting flux by terraform, the resources (pod/hr/namespace .etc) which in `config` folder and created by flux will not be deleted.

How do I delete these resources with flux both?

Thanks

**Comment by kingdonb** [comment]
The other suggestion I was going to make, since I wasn't sure how to read your question... if you uninstalled Flux and now the resources are left behind, it's not very helpful to tell what you could have done to make those resources go away for delete too.

If what you wanted was really, to be able to find and identify those resources now, you can just look for the resources with the labels `helm.toolkit.fluxcd.io/name` or `kustomize.toolkit.fluxcd.io/name` – those are all the resources that were created by Flux. Now you can look for resources with those labels, and know that they were likely created by Flux. This is not fool-proof though, since others can put those labels on their resources, and certain processes might even copy labels from one place to another. But if you were really just asking how to clean up after an experiment, this might also help now.
