### ISSUE TITLE
GA `flux_bootstrap_git`

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/terraform-provider-flux#426]
This umbrella issue tracks the work required to GA the `flux_bootstrap_git` resource.

Tasks:

- [x] e2e tests for `flux_bootstrap_git` using GitHub and Kubernetes Kind 
- [x] promote `flux_bootstrap_git` as the recommended bootstrap procedure (Flux website & Terraform registry)
- [x] cleanup the docs section in https://registry.terraform.io/providers/fluxcd/flux/latest/docs (remove old guides)
- [x] deprecate `flux_install` and `flux_sync` data sources and point people to the [community Helm charts](https://github.com/fluxcd-community/helm-charts) for those that are using the data source without bootstrap

TODO guides:
- [x] Migration Guide
- [x] GitHub Guide
- [x] GitLab Guide

**Comment by smurfralf** [comment]
WRT task 4 "deprecate `flux_install` ... " I want to note that our way of working uses the `flux_install` data source without the `flux_sync` data source to deploy flux. This is in order to explicitly control what and when deployments/upgrades happen using similar techniques as our other fundamental services. So while `flux_bootstrap_git` may be a full replacement for `flux_install + flux_sync`, it would be good if standalone use of `flux_install` is not deprecated.

**Comment by stefanprodan** [comment]
Instead of `flux_install` people can use the [community Helm charts](https://github.com/fluxcd-community/helm-charts) and deploy Flux without bootstrapping using the Helm TF provider.  The sole purpose of the terraform-provider-flux is to enable bootstrap the same way the Flux CLI does it.

**Comment by smurfralf** [comment]
@stefanprodan @phillebaba Agree with your observations about limitations of flux_install. We'll take a look at migrating to the helm chart. It looks like it is pretty well maintained even though its readme starts with "These helm charts are maintained and released by the fluxcd-community on a best effort basis."

**Comment by nick4fake** [comment]
I have just finished setting up cluster following https://registry.terraform.io/providers/fluxcd/flux/latest/docs/guides/gitlab just to *randomly* notice it is going to be deprecated. Could you please update docs to at least mention it?
