### ISSUE TITLE
Error while bootstrapping a git repository using flux terraform provider.

### ISSUE THREAD

**Issue by ramneekgupta91** [fluxcd/terraform-provider-flux#459]
### Discussed in https://github.com/fluxcd/flux2/discussions/3843

<div type='discussions-op-text'>

<sup>Originally posted by **ramneekgupta91** May  3, 2023</sup>
Hello Community,

I am migrating from flux v1 to flux v2. So first I tested everything using the flux cli and it worked fine. Now i am trying to bootstrap a git repository using the terraform flux provider version 0.25.3 and it gets stuck in the "still creating" state indefinitely.

On checking the logs, i see this error -> unexpected data: registry.terraform.io/fluxcd/flux:stderr="E0503 12:59:52.849426   11920 memcache.go:238] couldn't get current server API group list: <nil>"

K8s version : 1.25
Terraform version: 1.3.3

Provider versions:
fluxcd/flux: v0.25.3
hashicorp/aws: v4.65.0
hashicorp/kubernetes: v2.20.0

Is this a know issue ? Am i missing something ?

Below is my code:

`provider "flux" {
  kubernetes = {
    host                   = "endpoint here"
    cluster_ca_certificate = base64decode(local.ca_cert)
    exec = {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "aws"
      args        = ["eks", "get-token", "--cluster-name", "cluster name" , "--profile" , "cha-k8s-admin"  ]
      env         = {
        AWS_PROFILE = "cha-k8s-admin"
      }
    }
  }

  git = {
    url    = "local.url"
    branch = "master"
    ssh = {
      private_key = file("./keys/id_rsa_flux")
    }
  }
}

resource "flux_bootstrap_git" "fluxv2repo" {
  path             = "cha-sre-eks-5"
  components_extra = ["image-reflector-controller", "image-automation-controller"]
}

` </div>

**Comment by swade1987** [comment]
Hello @ramneekgupta91  ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

----

If you have already bootstrapped your cluster I would highly recommend deploying flux2 using the upstream helm chart, see example [here](https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/helm-install) and not using the `flux_bootstrap_git` resource. This resource expects a fresh cluster and fresh repository which you don't have.

**Comment by ramneekgupta91** [comment]
Thank you Steve for reaching out.
This issue can be closed for now as after further investigation the problem was not because of fluxcd. 
It was a connection issue b/w our terraform repo and the fluxcd git repo.
