### ISSUE TITLE
`flux-system` secret is not commited

### ISSUE THREAD

**Issue by norman-zon** [fluxcd/terraform-provider-flux#526]
Why is the `flux-system` kubernetes secret, that is created when bootstrapping not added to `gotk-components.yaml`?

With the current design, if the secret was deleted from the cluster after bootstrapping, the whole flux install would break and one would have to bootstrap from scratch.

**Comment by kingdonb** [comment]
The `flux-system` secret is typically an SSH private key, and the design of Flux is such that bootstrap is used as the installer (and the re-installer). You do not need to reinstall if only the secret was deleted from the cluster though, you can use `flux create secret git flux-system` to recreate it, then manually add the secret to the deploy keys.

If the secret was added to the git repo, it would (a) have to be stored unencrypted, which is a no-go, or (b) it would create a chicken-and-egg problem. How do you decrypt the secret when no Flux resources have been applied? We don't suggest to enable KMS or other decryption strategies on the `flux-system` bootstrap kustomization sync, because it can interfere with the bootstrap.

(Unless you're using KMS, and probably even then, it wouldn't be feasible to do decryption until after Flux is bootstrapped so any secrets or roles can be applied. If Flux is the first thing on the cluster, then there can be no root decryption key unless someone applies it manually ahead of time. But lack of decryption key should never fail bootstrap so we don't recommend decryption in the `flux-system` kustomization at all.)

Either way, you are handling secrets manually. But the flux-system secret isn't stored intentionally in the git repository, (why would someone delete it from the cluster?)

Let's say they did, why not just bootstrap again? Bootstrap is idempotent, it is designed to be used for repairs or upgrades.

**Comment by norman-zon** [comment]
Thanks a lot for the detailed explanation of the rationale behind this design. I can completely understand the decision to implement it that way. 

> Bootstrap is idempotent

was the part of the concept I hadn't wrapped my head around. Maybe this could be added to the docs?

Considering your answer, I decided to manage the secret as a terraform resource and set `disable_secret_creation = true`.

**Comment by kingdonb** [comment]
The flux bootstrap docs do indeed mention this trait somewhat prominently:

https://fluxcd.io/flux/installation/#bootstrap

Thanks for follow-up and closing! And thanks for using Flux!
