### ISSUE TITLE
flux_bootstrap_git kustomization_override path is incorrectly created on windows with terraform

### ISSUE THREAD

**Issue by brokenjacobs** [fluxcd/terraform-provider-flux#535]
We have an issue where plans generated by terraform on windows are changing our kustomization file paths. Every plan looks like this from windows after a linux/osx/etc apply:
```
+ "clusters\\nonprod-dw-gke\\flux-system\\kustomization.yaml"
- "clusters/nonprod-dw-gke/flux-system/kustomization.yaml"
```

Which is quite annoying. Somehow the git path is being created with an OS aware path spec?

**Comment by brokenjacobs** [comment]
It doesn't appear that any new files are committed to git when this happens, just a statefile update with the oddly formatted path.

**Comment by swade1987** [comment]
Hello @anupclouddevops ,

I hope you're doing well! I'm the newest contributor to this repository, and I'm currently in the process of issue grooming to ensure that all concerns are addressed promptly and efficiently.

I noticed this issue you reported and wanted to check in with you to see if it's still affecting your work. Your feedback is invaluable to us, and any additional insights or updates you can share would be greatly appreciated to help us understand and solve the problem more effectively.

If this issue has been resolved, could you please share how it was fixed? This information could be incredibly helpful to others in the community facing similar problems. It would also allow us to close this issue with a clear resolution.
In case the issue is still open and troubling you, let's work together to find a solution. Your satisfaction and the smooth functioning of our project are our top priorities.

Thank you for your time and contributions to our community. Looking forward to your response!

Best regards,

Steve

----

The recommended approach for this is to use `kustomization_override` in the `flux_bootstrap_git` resource. An example of this can be found [here](https://registry.terraform.io/providers/fluxcd/flux/latest/docs/resources/bootstrap_git#kustomization_override) and [here](https://github.com/fluxcd/terraform-provider-flux/blob/main/examples/github-with-inline-customizations/main.tf#L60).

**Comment by brokenjacobs** [comment]
AFAIK the rewrite of the terraform provider resolved this issue. This was only a problem with the old style bootstrapping.
