### ISSUE TITLE
Github Enterprise - how to change the branch of GitRepository in flux-system/gotk-sync.yaml from "main" to "master"

### ISSUE THREAD

**Issue by brant4test** [fluxcd/terraform-provider-flux#63]
**Version**:
terraform-provider-flux v0.0.7
github version 3.1.0

**Updating "branch" here didn't work**
https://github.com/fluxcd/terraform-provider-flux/blob/19ff7cea827bfe84a268cacb15e4e20b4a6b54a6/examples/github/variables.tf#L19

**Steps of what I've done:** 

1. Following sample here:
https://github.com/fluxcd/terraform-provider-flux/tree/v0.0.7/examples/github

2. Replaced "github_owner" below with "github_base_url"  and "github_organization" for GHE:
https://github.com/fluxcd/terraform-provider-flux/blob/19ff7cea827bfe84a268cacb15e4e20b4a6b54a6/examples/github/variables.tf#L1

3. Update flux_sync below for GHE:
https://github.com/fluxcd/terraform-provider-flux/blob/19ff7cea827bfe84a268cacb15e4e20b4a6b54a6/examples/github/main.tf#L48

Furthermore, using later version of github provider, say 4.1.0 would bring this Warning
```
Warning: "default_branch": [DEPRECATED] Use the github_branch_default resource instead

  on main.tf line 144, in resource "github_repository" "main":
144: resource "github_repository" "main" {
```

 Thanks!

**Comment by phillebaba** [comment]
So are you saying the GitRepository resource does not set the correct branch when you pass "master" as the branch name to the sync datasource?

**Comment by brant4test** [comment]
yes, not updated in gotk-sync.yaml file

**Comment by phillebaba** [comment]
You are right the value does not seem to update, this is obviously a bug so let me explore what is causing it.

**Comment by brant4test** [comment]
Thanks for your quick response!

Btw, just bring this extra question for brainstorming:

"GitHub Terraform provider will not touch existing GitHub repositories, so it is safe to adopt gradually. "

But "Terraform destroy" will DELETE Terraform bootstrapped Flux2 repository, which could be the "GitOps config repository", right? 

From my understanding, wouldn't be more practical to leave this repository alone even if Flux Toolkit got deleted on a Kubernetes cluster?  Welcome your comments!

**Comment by phillebaba** [comment]
I guess its a sign that it is soon lunch time. The problem is not because of a bug but because of bad documentation written by.... myself. In the GitHub example I did not set the branch in the flux_sync resource. Doing this will solve your problem.
```
data "flux_sync" "main" {
  target_path = var.target_path
  url         = "ssh://git@github.com/${var.github_owner}/${var.repository_name}.git"
  branch = var.branch
}
```

Thank you for reporting the problem, I will create a PR that fixes the examples :cake: 

Regarding your second question you are correct and it mostly for demonstration purposes that we create a repository. In my cluster deployment I create the repositories manually and use a data source to use the repositories. One of the reasons for doing this is as you said, removing the risk of randomly deleting config that has been comitted after the repo creation. The other is that most people will have a multi environment setup where they use the same repo but different directories. Making it difficult in terraform to only create the repo once if each environment has its own state.

Feel free to ping me in Slack if you have any other questions :smile:

**Comment by brant4test** [comment]
I see, thanks a lot!  
👍
